In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("datasets/student_dataset_10000_rows.csv")
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [4]:
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  str
dtypes: float64(1), int64(6), str(1)
memory usage: 625.1 KB

In [6]:
df.isnull().sum()

study_hours              0
attendance               0
sleep_hours              0
internet_usage           0
assignments_completed    0
previous_score           0
exam_score               0
placement_status         0
dtype: int64

HANDLE MISSING VALUES

In [7]:
df.fillna(df.mean(numeric_only=True), inplace=True)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

VERIFY MISSING VALUES REMOVED

In [8]:
df.isnull().sum()

study_hours              0
attendance               0
sleep_hours              0
internet_usage           0
assignments_completed    0
previous_score           0
exam_score               0
placement_status         0
dtype: int64

CHECK COLUMN NAMES

In [9]:
df.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='str')

CHECK DATA TYPES

In [10]:
df.dtypes

study_hours                int64
attendance                 int64
sleep_hours                int64
internet_usage             int64
assignments_completed      int64
previous_score             int64
exam_score               float64
placement_status             str
dtype: object

CONVERT CATEGORICAL DATA

In [11]:
df["placement_status"]=df["placement_status"].map({"Placed":1,"Not Placed":0})

VERIFY CONVERSION

In [12]:
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,1
1,4,69,5,3,8,56,100.00,1
2,11,60,7,6,10,45,100.00,1
3,8,99,9,8,4,55,90.17,1
4,5,52,8,6,8,40,78.82,1

IMPORT STANDARD SCALER

In [13]:
from sklearn.preprocessing import StandardScaler

APPLY SCALING

In [15]:
scaler=StandardScaler()
scaled_data=scaler.fit_transform(df)
df_scaled=pd.DataFrame(scaled_data, columns=df.columns)
df_scaled.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,0.319400,-0.788197,0.878446,0.298725,0.001922,-0.166322,0.882994,0.443559
1,-0.628937,-0.050217,-0.876691,-0.975970,-0.329541,-0.509138,0.882994,0.443559
2,1.583850,-0.561126,0.293400,-0.019949,0.001922,-1.137632,0.882994,0.443559
3,0.635513,1.652815,1.463492,0.617398,-0.992469,-0.566273,0.230169,0.443559
4,-0.312825,-1.015268,0.878446,-0.019949,-0.329541,-1.423311,-0.523602,0.443559

SAVE CLEANED DATASET

In [16]:
df_scaled.to_csv("outputs/cleaned_data.csv", index=False)